import { useState, useEffect } from 'react'
import { X } from 'lucide-react'

// Deterministic pseudo-random rotation per photo number (not Math.random --
// stays stable across re-renders instead of jittering).
function rotateFor(n) {
  return ((n * 37) % 9) - 4 // -4..4 degrees
}

// Belt tiles point at /thumbs/{n}.jpg -- generated by generate-thumbnails.js,
// always .jpg regardless of the source extension, so no png/jpg fallback
// needed here (unlike the full-res lightbox below, where the ORIGINAL could
// still be either extension). If a thumbnail doesn't exist yet (script not
// run, or that number not uploaded), the tile just quietly doesn't render.
function PhotoTile({ n, onOpen }) {
  const [hidden, setHidden] = useState(false)
  if (hidden) return null

  return (
    <button
      type="button"
      className="photo-reel-tile"
      style={{ '--tile-rotate': `${rotateFor(n)}deg` }}
      onClick={() => onOpen(n)}
      aria-label={`View photo ${n} full size`}
    >
      <img
        src={`/thumbs/${n}.jpg`}
        alt=""
        onError={() => setHidden(true)}
        loading="lazy"
        decoding="async"
        draggable={false}
      />
    </button>
  )
}

function Lightbox({ n, onClose }) {
  const [ext, setExt] = useState('png')
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    function onKey(e) {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  function handleError() {
    if (ext === 'png') setExt('jpg') // full-res original could be either extension
    else setFailed(true)
  }

  return (
    <div
      className="photo-lightbox-backdrop"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-label="Full size photo"
    >
      <button type="button" className="photo-lightbox-close" onClick={onClose} aria-label="Close">
        <X size={20} />
      </button>
      {!failed && (
        <img
          src={`/${n}.${ext}`}
          alt=""
          className="photo-lightbox-img"
          onError={handleError}
          onClick={(e) => e.stopPropagation()}
        />
      )}
    </div>
  )
}

// count=20 by default. Numbers alternate between two rows scrolling
// opposite directions. Missing numbers are skipped automatically -- safe
// to have fewer than 20 uploaded and add the rest later.
export default function PhotoReel({ count = 20 }) {
  const [openPhoto, setOpenPhoto] = useState(null)
  const numbers = Array.from({ length: count }, (_, i) => i + 1)
  const rowA = numbers.filter((_, i) => i % 2 === 0)
  const rowB = numbers.filter((_, i) => i % 2 === 1)

  return (
    <div className="photo-reel">
      <div className="photo-reel-row photo-reel-row-left">
        <div className="photo-reel-track">
          {[...rowA, ...rowA].map((n, i) => (
            <PhotoTile key={`a-${n}-${i}`} n={n} onOpen={setOpenPhoto} />
          ))}
        </div>
      </div>
      <div className="photo-reel-row photo-reel-row-right">
        <div className="photo-reel-track">
          {[...rowB, ...rowB].map((n, i) => (
            <PhotoTile key={`b-${n}-${i}`} n={n} onOpen={setOpenPhoto} />
          ))}
        </div>
      </div>
      {openPhoto && <Lightbox n={openPhoto} onClose={() => setOpenPhoto(null)} />}
    </div>
  )
}
